//! The Minecraft map: a world generated by MinecraftOSS, played on top of a
//! small IW4 map loaded only for the shared weapon, body and menu content.
//! None of that map's world is shown or collided with.
use crate::{GamesRoot, ZoneFile};

pub const ZONE: &str = "minecraft:overworld";
const PROXY_ZONE: &str = "iw4:mp_rust";

pub fn is_minecraft(zone: &str) -> bool {
    zone.eq_ignore_ascii_case(ZONE)
}

/// The MinecraftOSS checkout the world is generated from, when configured.
pub fn root() -> Option<std::path::PathBuf> {
    let root = std::path::PathBuf::from(std::env::var_os("MINECRAFTOSS_ROOT")?);
    root.join("datapacks").is_dir().then_some(root)
}

pub fn find_zone_file(root_dir: &GamesRoot, zone: &str) -> Result<ZoneFile, String> {
    if !is_minecraft(zone) {
        return asset_transport::find_zone_file(root_dir, zone);
    }
    let checkout = root().ok_or("MINECRAFTOSS_ROOT is not set to a MinecraftOSS checkout")?;
    let mut proxy = asset_transport::find_zone_file(root_dir, PROXY_ZONE)?;
    proxy.zone_name = ZONE.to_owned();
    proxy.alias_note = Some(format!("Minecraft world from {}", checkout.display()));
    Ok(proxy)
}

pub fn list_mp_maps(root_dir: &GamesRoot) -> Vec<String> {
    let mut maps = asset_transport::list_mp_maps(root_dir);
    if root().is_some() && asset_transport::find_zone_file(root_dir, PROXY_ZONE).is_ok() {
        maps.push(ZONE.to_owned());
    }
    maps.sort();
    maps.dedup();
    maps
}
